# 2. Statistical Learning

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import interpolate

In [2]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


## 2.1 What Is Statistical Learning?

**Statistical Learning** - a set of approaches for estimating a function $f(X)$ from a set of data.

### FIGURE 2.1.

In [4]:
# advertising = pd.read_csv('http://faculty.marshall.usc.edu/gareth-james/ISL/Advertising.csv')
advertising = pd.read_csv('https://raw.githubusercontent.com/gitony0101/X4DS/main/data/Advertising.csv', index_col=0)
advertising.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [ ]:
# advertising.describe()

In [5]:
_, axes = plt.subplots(1, 3, figsize=(12, 5), constrained_layout=True)

sns.regplot(data=advertising,
            x='TV',
            y='sales',
            scatter_kws={'color': 'red'},
            ax=axes[0])
sns.regplot(data=advertising,
            x='radio',
            y='sales',
            scatter_kws={'color': 'red'},
            ax=axes[1])
sns.regplot(data=advertising,
            x='newspaper',
            y='sales',
            scatter_kws={'color': 'red'},
            ax=axes[2])

More generally, suppose that we observe a quantitative response $Y$ and $p$ different predictors, $X_{1}, X_{2}, \ldots, X_{p} $.

We assume that there is some relationship between $Y$ and $X=\left(X_{1}, X_{2}, \ldots, X_{p}\right)$, which can be written in the very general form:


$$
Y=f(X)+\epsilon
$$


The symbol $f$ represents the systematic information that $X$ provides about $Y$. Statistical learning refers to a set of approaches for estimating $f$.

### FIGURE 2.2.

In [6]:
# income = pd.read_csv('http://faculty.marshall.usc.edu/gareth-james/ISL/Income1.csv')
income = pd.read_csv('https://raw.githubusercontent.com/gitony0101/X4DS/main/data/Income1.csv', index_col=0)
income.head()

Education     Income
1  10.000000  26.658839
2  10.401338  27.306435
3  10.842809  22.132410
4  11.244147  21.169841
5  11.645485  15.192634

In [7]:
_, axes = plt.subplots(1, 2, figsize=(10, 5), constrained_layout=True)


for i in range(2):

    g = sns.scatterplot(data=income,
                         x='Education',
                         y='Income',
                         color='red',
                         ax=axes[i])
    g.set(xlabel='Years of Education')


lowess = sm.nonparametric.lowess(endog=income.Income,
                                 exog=income.Education,
                                 frac=0.5)

axes[1].plot(lowess[:, 0], lowess[:, 1])

axes[1].vlines(x=lowess[:, 0],
               ymin=np.fmin(income.Income, lowess[:, 1]),
               ymax=np.fmax(income.Income, lowess[:, 1]))

## Why estimate $f$?

Either for **prediction** or **inference**.

### Prediction 

The set of inputs X are readily available, but the output Y cannot easily be obtained. We wish to predict what Y will be given a set of inputs X

$$
\hat{Y}=\hat{f}(X)
$$


The accuracy of the prediction depends on two quantities - **the reducible and the irreducible error**. The estimate $\hat{f}(X)$
will not be a perfect estimate for the **true** $f(X)$

We can reduce the error by using better statistical learning techniques.
However the variability of $ϵ$ also affects the accuracy of the predictions. This is the irreducible error.

Consider a given estimate $\hat{f}$ and a set of predictors $X$, which yields the prediction $\hat{Y}=\hat{f}(X)$. Assume for a moment that both $\hat{f}$ and $X$ are fixed. Then, it is easy to show that

$$
\begin{aligned}
E(Y-\hat{Y})^{2} &=E[f(X)+\epsilon-\hat{f}(X)]^{2} \\
&=\underbrace{[f(X)-\hat{f}(X)]^{2}}_{\text {Reducible }}+\underbrace{\operatorname{Var}(\epsilon)}_{\text {Irreducible }}
\end{aligned}
$$

where $E(Y-\hat{Y})^{2}$ represents the average, or expected value, of the squared difference between the predicted and actual value of $Y$, and $\operatorname{Var}(\epsilon)$ represents the variance associated with the error term $\epsilon$.



### Inference

We are often interested in the way that Y
is affected by changes in X. We need to estimate $f(X)$, but we don’t want to predict Y. We instead want to understand the relationship betrween X and Y.

### FIGURE 2.3.

**3D plotting is never an easy job**

In [8]:
# income = pd.read_csv('http://faculty.marshall.usc.edu/gareth-james/ISL/Income2.csv')
income2 = pd.read_csv('https://raw.githubusercontent.com/gitony0101/X4DS/main/data/Income2.csv', index_col=0)
income2.head()

Education   Seniority     Income
1  21.586207  113.103448  99.917173
2  18.275862  119.310345  92.579135
3  12.068966  100.689655  34.678727
4  17.034483  187.586207  78.702806
5  19.931034   20.000000  68.009922

In [9]:
formula = "Income ~ Education + Seniority + Education*Seniority"
result = smf.ols(formula=formula, data=income2).fit()
print(result.params)

Intercept             -57.176806
Education               6.345990
Seniority               0.255030
Education:Seniority    -0.005072
dtype: float64


In [10]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 Income   R-squared:                       0.936
Model:                            OLS   Adj. R-squared:                  0.928
Method:                 Least Squares   F-statistic:                     126.1
Date:                Sun, 25 Jul 2021   Prob (F-statistic):           1.31e-15
Time:                        13:42:45   Log-Likelihood:                -99.792
No. Observations:                  30   AIC:                             207.6
Df Residuals:                      26   BIC:                             213.2
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept             -57.1768     10.753     -5.317      0.000     -79.279     -35.074
Education               6.3460      0.670      9.475      0.000       4.969       7.723
Seniority               0.2550      0.106      2.406      0.024       0.037       0.473
Education:Seniority    -0.0051      0.006     -0.797      0.433      -0.018       0.008
==============================================================================
Omnibus:                        3.209   Durbin-Watson:                   2.137
Prob(Omnibus):                  0.201   Jarque-Bera (JB):                2.710
Skew:                           0.725   Prob(JB):                        0.258
Kurtosis:                       2.746   Cond. No.                     1.54e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.54e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

### FIGURE 2.4.

In [11]:
fig = plt.figure(figsize=(8, 8))
ax = fig.add_subplot(111, projection='3d')

xx = income2['Education']
yy = income2['Seniority']
zz = income2['Income']

def generate_mesh2d(array):
     
    new_array = []
    
    for i in range(len(array)):
        
        # 如下生成meshgrid数据，并保证xx和yy一定出现在meshgrid中
        x_space = (array[i].max() - array[i].min()) / 30
        xx_sort = np.sort(array[i])
        
        n = len(array[i])
        XX = [array[i].min()]
        
        for i in range(n - 1):
            space = xx_sort[i + 1] - xx_sort[i]
            # 加判断，< 1 时，区间 * 2
            n_interval = int(space // x_space)
            seq = list(np.linspace(xx_sort[i], xx_sort[i + 1], n_interval + 1))
            XX.extend(seq[1:])

        XX = np.array(XX)
        new_array.append(XX)
        
    return new_array

XX, YY = generate_mesh2d([xx, yy])
X, Y = np.meshgrid(XX, YY)

exog = pd.DataFrame({'Education': X.ravel(), 'Seniority': Y.ravel()})
Z = np.array(result.predict(exog=exog)).reshape(X.shape)

ax.plot_surface(X=X, Y=Y, Z=Z, rcount=1, ccount=1, color='#F2D711', alpha=0.8)
ax.plot_wireframe(X=X,
                  Y=Y,
                  Z=Z,
                  rstride=1,
                  cstride=1,
                  lw=0.2,
                  color='k',
                  alpha=1)

ax.scatter3D(xs=xx, ys=yy, zs=zz, color='r', alpha=1)

# 画误差线
for value1, value2, value3 in zip(xx, yy, zz):
    idxx = np.argmin(np.abs(XX - value1))
    idxy = np.argmin(np.abs(YY - value2))
    X0 = XX[idxx]
    Y0 = YY[idxy]
    Z0 = Z[idxy, idxx]
    ax.plot3D((value1, X0), (value2, Y0), (value3, Z0), 'black')

ax.zaxis._axinfo['juggled'] = (1, 2, 0)
ax.set(xlabel='Years of Education', ylabel='Seniority', zlabel='Income')
ax.xaxis.pane.set_alpha(1)
ax.yaxis.pane.set_alpha(1)
ax.zaxis.pane.set_alpha(1)
ax.xaxis.pane.set_edgecolor('black')
ax.yaxis.pane.set_edgecolor('black')
ax.zaxis.pane.set_edgecolor('black')
ax.xaxis.pane.set_fc('white')
ax.yaxis.pane.set_fc('white')
ax.zaxis.pane.set_fc('white')
ax.grid(0)
plt.show()

/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


### FIGURE 2.5.

<img src=https://d3i71xaburhd42.cloudfront.net/7a9dadfbb012558b192ac3819b6ecdbd09d9fa22/9-Figure2.5-1.png>

A smooth thin-plate spline fit to the Income data from Figure 2.3 is shown in yellow; the observations are displayed in red. Splines are discussed in Chapter 7. 

### FIGURE 2.6.

<img src=https://d3i71xaburhd42.cloudfront.net/7a9dadfbb012558b192ac3819b6ecdbd09d9fa22/10-Figure2.6-1.png>

FIGURE 2.6. A rough thin-plate spline fit to the Income data from Figure 2.3. This fit makes zero errors on the training data. 

### FIGURE 2.7.

<img src=https://marcfbellemare.com/wordpress/wp-content/uploads/2019/01/JamesFigure.jpg>

### FIGURE 2.8.

<img src=https://d3i71xaburhd42.cloudfront.net/7a9dadfbb012558b192ac3819b6ecdbd09d9fa22/13-Figure2.8-1.png>
    
    A clustering data set involving three groups. Each group is shown using a different colored symbol. Left: The three groups are well-separated. In this setting, a clustering approach should successfully identify the three groups. Right: There is some overlap among the groups. Now the clustering task is more challenging.

SNS KNN

A clustering data set involving three groups. Each group is shown using a different colored symbol. Left: The three groups are well-separated. In this setting, a clustering approach should successfully identify the three groups.

Right: There is some overlap among the groups. Now the clustering task is more challenging.

## 2.2 Assessing Model Accuracy

Every data set is different and there is no one statistical learning method that works best for all data sets. It is important for any given data set to find the statistical learning method that produces the best results. This section presents some concepts that are part of that decision-making process.

### Measuring the Quality of Fit

#### [MSE:Mean Squared Error](https://en.wikipedia.org/wiki/Mean_squared_error)

<img src=https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e>

**Proof of variance and bias relationship:**

<img src=https://wikimedia.org/api/rest_v1/media/math/render/svg/98c253fd2ab03bfc46743f5524b7fd060a94f4f6>

**Proff:**
<img src=https://wikimedia.org/api/rest_v1/media/math/render/svg/2ac524a751828f971013e1297a33ca1cc4c38cd6>

Alternatively, we have:

<img src=https://wikimedia.org/api/rest_v1/media/math/render/svg/632fe180f618ad29d879f08fa21a88bda3e44876>

In regression, mean squared error (MSE) is the most commonly-used measure. A small MSE indicates the predicted responses are very close to the true ones. MSE used on training data is more accurately referred to as the training MSE.

We are most concerned with the accuracy of the predictions when we apply our methods to previously unseen data. If you are trying to predict the value of a stock, your concern is how it performs in the future, not on known data from the past. Thus, the goal is then minimizing the test MSE, which measures the accuracy of a model on observations that were not used to train the model. Imagine a set of observations (x0,y0)
that were not used to train the statistical learning method.


$$Ave(y_0 - \hat{f}(x_0))^2$$

### FIGURE 2.9

<img src=https://d3i71xaburhd42.cloudfront.net/7a9dadfbb012558b192ac3819b6ecdbd09d9fa22/17-Figure2.9-1.png>
    
    Left: Data simulated from f , shown in black. Three estimates of f are shown: the linear regression line (orange curve), and two smoothing spline fits (blue and green curves). Right: Training MSE (grey curve), test MSE (red curve), and minimum possible test MSE over all methods (dashed line). Squares represent the training and test MSEs for the three fits shown in the left-hand panel.

### FIGURE 2.10

<img src=https://d3i71xaburhd42.cloudfront.net/7a9dadfbb012558b192ac3819b6ecdbd09d9fa22/19-Figure2.10-1.png>
    
     Details are as in Figure 2.9, using a different true f that is much closer to linear. In this setting, linear regression provides a very good fit to the data. 

### The Bias-Variance Trade-Off

The expected test MSE can be broken down into the sum of three quantities:

1. the variance of $\hat{f}\left(x_{0}\right)$
2. the squared bias of $\hat{f}\left(x_{0}\right)$
3. the variance of the error terms $\varepsilon$
$$
E\left(y_{0}-\hat{f}\left(x_{0}\right)^{2}=\operatorname{Var}\left(\hat{f}\left(x_{0}\right)\right)+\left[\operatorname{Bias}\left(\hat{f}\left(x_{0}\right)\right)\right]^{2}+\operatorname{Var}(\varepsilon)\right.
$$

### FIGURE2.11

<img src=https://d3i71xaburhd42.cloudfront.net/7a9dadfbb012558b192ac3819b6ecdbd09d9fa22/20-Figure2.11-1.png>

Details are as in Figure 2.9, using a different f that is far from linear. In this setting, linear regression provides a very poor fit to the data. 

### FIGURE 2.12

<img src=http://www.rnfc.org/courses/isl/Lesson%202/Summary/Figures/Figure2-12.png>    
     Squared bias (blue curve), variance (orange curve), Var( ) (dashed line), and test MSE (red curve) for the three data sets in Figures 2.92.11. The vertical dotted line indicates the flexibility level corresponding to the smallest test MSE.

### The Classification Setting

#### Bayes classifier

For training observations $\{(x_1, y_1), \ldots , (x_n, y_n)\}$, where $y_1, \ldots , y_n$ are qualitative, the training error rate is used to quantify the accuracy of a model. The proportion of mistakes when $\hat{f}$ is used on the training observations is given by $\label{eq:trainingErr} \frac{1}{n}\sum\limits_{i=1}^n{I(y_i \neq \hat{y}_i)}\tag{2.8}$
where $\hat{y}_i$ is the predicted class of observation $i$ using $\hat{f}$ and $I(y_i \neq \hat{y}_i)$ is an indicator variable equal to 1 when $y_i \neq \hat{y}_i$ and 0 when $y_i = \hat{y}_i$. When $I(y_i \neq \hat{y}_i) = 0$, observation $i$ was correctly classified and when $I(y_i \neq \hat{y}_i) = 1$, observation $i$ was misclassified.

Equation $\eqref{eq:trainingErr}$ is called the training error rate. As before, the test error rate is more important and for a set of test observations of the form $(x_0, y_0)$ and is given by
$\mathrm{Avg}(I(y_0 \neq \hat{y}_0)),\tag{2.9}$

where $\hat{y}_0$ is the class prediction of test observation with predictor $x_0$. The best classifier has the lowest test error. The test error rate is lowest, on average, when test observations $x_0$ are assigned to class $j$ when $\Pr(Y = j \mid X = x_0)\tag{2.10}$ is largest. This is called the Bayes classifier.

### FIGURE 2.13

Example

Consider predictor $X = (X_1, X_2)$. In Figure 2.13, the orange and blue circles represent training observations from two classes. For each $X$, there is a probability that the response is orange or blue. Since this data was computer generated, we can calculate conditional probabilities for each $X$ The orange region reflects points where $\Pr(Y=\text{orange} \mid X) > 0.5$, while blue reflects points where the probability is less than 50%. The purple dashed line indicates 50% probabilities. This line is called the Bayes decision boundary.

<img src=http://www.rnfc.org/courses/isl/Lesson%202/Summary/Figures/Figure2-13.png>

Figure 2.13 – Simulated data set of 100 observations in each of two groups indicated by blue and orange. The purple dashed line is the Bayes decision boundary.

#### KNN-K-Nearest Neighbors

$$Pr(Y = j| X = x_0) = 1/K\sum_{i\in N_0}I(y_i = j)$$

In theory we would always like to predict qualitative responses using the Bayes classifier. But for real data, we do not know the conditional distribution of Y given X, and so computing the Bayes classifier is impossible. Therefore, the Bayes classifier serves as an unattainable gold standard against which to compare other methods. Many approaches attempt to estimate the conditional distribution of Y given X, and then classify a given observation to the class with highest estimated probability. One such method is the K-nearest neighbors (KNN) classifier. Given a positive inK-nearest neighbors teger K and a test observation x0, the KNN classifier first identifies the K points in the training data that are closest to x0, represented by N0.
It then estimates the conditional probability for class j as the fraction of points in N0whose response values equal j:

### Figure 2.14 



Figure 2.14  illustrates the KNN classifier. In the left panel, training data with six blue and six orange points is used to classify the black x. For $K = 3$, KNN finds the three points nearest the cross (indicated by the green circle). Since there are two blue points and one orange point inside the green circle, KNN predicts that the black x is blue with probability $2/3$ and orange with probability $1/3$. Since there is a high probability of the black x being blue, KNN classifies it as blue. The right hand panel shows how KNN would classify any point for all possible $X_1$ and $X_2$ with $K = 3$. The KNN decision boundary is shown by the black curve.

<img src=http://www.rnfc.org/courses/isl/Lesson%202/Summary/Figures/Figure2-14.png>

Figure 2.14 – Example of KNN with $K = 3$. The KNN decision boundary is illustrated in the right panel by the black curve.

The value of $K$ has a significant impact on the KNN classifier. Figure 2.16 shows KNN fits for $k = 1$ (left) and $K = 100$ (right). When $K = 1$, the decision boundary is too flexible and results in low bias and high variance. As $K$ increases, flexibility increases, which results in a near linear decision boundary. High $K$ produces a low variance and high-bias classifier.


### Figure 2.16
<img src=http://www.rnfc.org/courses/isl/Lesson%202/Summary/Figures/Figure2-16.png>


Figure 2.16 – Example of KNN for $K = 1$ and $K = 100$. The Bayes decision boundary is shown by the purple dashed line and the KNN decision boundary is the solid black curve.

A comparison of the test and training error rates for varying values of $K$ is shown in Figure 2.17. As $1/K$ rises (as $K$ decreases), the method becomes more flexible. The test error conforms with the results above and is a U-shape, declining until a minimum at roughly $K = 10$ before increasing as flexibility causes overfitting


### Figure 2.17

<img src=http://www.rnfc.org/courses/isl/Lesson%202/Summary/Figures/Figure2-17.png>

Figure 2.17 – The KNN training error rate (blue) and test error rate (orange) as the level of flexibility increases.

## 2.3 Lab: Introduction to Python

Python uses functions to perform operations. To run a function called `funcname`, we type `funcname(input1, input2)`, where the inputs (or _arguments_) `input1` and `input2` tell Python how to run the function. A function can have any number of inputs. For example, to create a vector of numbers, we use the function `np.array()` from the module `NumPy`. To do this, we need to pass a `list` as an argument to the function, lists are a built-in data type in Python. Here we assume you are already familiar with basic Python objects.

In [ ]:
# Define a new vector x
x = np.array([1, 6, 2])
x

array([1, 6, 2])

Typing the `help(funcname)` will cause Jupyter to pop up a help panel with additional information about the function `funcname`.

In [ ]:
# help(np.array)

We now make a second vector `y`.

In [ ]:
y = np.array([1, 4, 3])

We can tell Python to add two sets of numbers together. It will then add the first number from `x` to the first number from `y`, and so on. However, `x` and `y` should be the same length. We can check their length using the `len()` function.

In [ ]:
len(x)

3

In [ ]:
len(y)

3

In [ ]:
x + y

array([ 2, 10,  5])

The "magic" `%whos` command allows us to look at a list of all the objects, such as data and functions, that we have saved so far.

In [ ]:
%whos

Variable          Type                        Data/Info
-------------------------------------------------------
X                 ndarray                     28x29: 812 elems, type `float64`, 6496 bytes
X0                float64                     17.0344827586207
XX                ndarray                     29: 29 elems, type `float64`, 232 bytes
Y                 ndarray                     28x29: 812 elems, type `float64`, 6496 bytes
Y0                float64                     106.896551724138
YY                ndarray                     28: 28 elems, type `float64`, 224 bytes
Z                 ndarray                     28x29: 812 elems, type `float64`, 6496 bytes
Z0                float64                     68.9506564687634
advertising       DataFrame                           TV  radio  newspa<...>n\n[200 rows x 4 columns]
ax                Axes3DSubplot               Axes3DSubplot(0.135,0.125;0.755x0.755)
axes              ndarray                     2: 2 elems, type `obj

The command `del` can be used to delete any that we don't want.

In [ ]:
# del x

In [ ]:
%whos

Variable          Type                        Data/Info
-------------------------------------------------------
X                 ndarray                     28x29: 812 elems, type `float64`, 6496 bytes
X0                float64                     17.0344827586207
XX                ndarray                     29: 29 elems, type `float64`, 232 bytes
Y                 ndarray                     28x29: 812 elems, type `float64`, 6496 bytes
Y0                float64                     106.896551724138
YY                ndarray                     28: 28 elems, type `float64`, 224 bytes
Z                 ndarray                     28x29: 812 elems, type `float64`, 6496 bytes
Z0                float64                     68.9506564687634
advertising       DataFrame                           TV  radio  newspa<...>n\n[200 rows x 4 columns]
ax                Axes3DSubplot               Axes3DSubplot(0.135,0.125;0.755x0.755)
axes              ndarray                     2: 2 elems, type `obj

It's also possible to remove all objects at once.

In [ ]:
# %reset

In [ ]:
# %whos

The `np.matrix()` function can be used to create a matrix of numbers. Before we use the `np.matrix()` function we can learn more about it.

In [ ]:
# help(np.matrix)

The help reveals that the `matrix()` function can take a number of inputs, but for now we focus on how to build a simple matrix. To build a matrix, we can input a list of lists as a parameter. Each list is a row.

In [ ]:
x = np.matrix([[1, 3], [2, 4]])
x

matrix([[1, 3],
        [2, 4]])

If `data` is a string, it is interpreted as a matrix with commas or spaces separating columns, and semicolons separating rows.

In [ ]:
x = np.matrix('1, 3; 2, 4')
x

matrix([[1, 3],
        [2, 4]])

The `np.sqrt()` function return the square root of each element of a vector or a matrix. The function `np.power(x, 2)` raises each element of `x` to the power of 2; any powers are possible, including fractional or negative powers.

In [ ]:
np.sqrt(x)

matrix([[1.        , 1.73205081],
        [1.41421356, 2.        ]])

In [ ]:
np.power(x, 2)

matrix([[ 1,  9],
        [ 4, 16]])

In [ ]:
from numpy import random

The `random.normal()` function generates a vector of random normal variables, with third argument `size` the sample size. Each time we call this function, we will get a different answer. Here we create two correlated sets of numbers, `x` and `y`, and use the `np.corrcoef()` function to compute the correlation matrix between them.

In [ ]:
x = random.normal(size=50)
y = x + random.normal(size=50, loc=50, scale=.1)
np.corrcoef(x, y)

array([[1.       , 0.9940011],
       [0.9940011, 1.       ]])

By default, `random.normal` creates random variables from standard normal distribution with mean of 0 and standard deviation of 1. However, the mean and standard deviation can be altered using the `loc` and `scale` arguments, as illustrated above. Sometimes we want our code to reproduce the exact same set of random numbers; we can use the `random.seed()` function to do this. The `random.seed()` function takes an (arbitrary) integer argument.

In [ ]:
random.seed(1303)
random.normal(size=50)

array([-0.03425693,  0.06035959,  0.45511859, -0.36593175, -1.6773304 ,
        0.5910023 ,  0.41090101,  0.46972388, -1.50462476, -0.70082238,
        1.43196963,  0.35474484,  1.67574682,  1.62741373,  0.27015354,
        0.15248539,  0.11593596,  0.89272237, -2.16627436,  0.26787192,
        0.36658207,  2.72335408,  0.44060293,  0.36036757,  0.38119264,
       -0.27845602,  1.73458476, -1.48138111, -0.47556927, -0.1932596 ,
        0.68115816, -0.05143463, -0.59151688,  0.02292374, -0.12259196,
        0.50633508,  0.63181139, -0.2443932 ,  0.39847385, -1.2716468 ,
        0.43167303, -1.36491646,  0.91004701,  0.65707308, -0.080445  ,
       -1.12057881, -1.31479423,  0.26394714, -0.59459381, -0.07624482])

We use `random.seed()` throughout the labs whenever we perform calculations involving random quantities in order to obtain reproducible results.

The `np.mean()` and `np.var()` functions can be used to compute the mean and variance of a vector of numbers. Applying `np.sqrt()` to the output of `np.var()` will give the standard deviation (or we can use `np.std()`).

In [ ]:
random.seed(3)
y = random.normal(size=100)
np.mean(y)

-0.10863707440606224

In [ ]:
np.var(y)

1.132081888283007

In [ ]:
np.std(y)

1.0639933685333791

### Graphics

The `plt.plot` function is the primary way to plot data in Python. For instance, `plt.plot(x, y, 'o')` produces a scatterplot of the numbers in `x` versus the numbers in `y`. There are many additional options that can be passed in to the `plt.plot()` function, and many other functions that alter the appearance of the plot. For example, the `ax.set(xlabel=)` function will result on a label in the x-axis. A format string consists of a part for color, marker and line: `fmt = '[marker][line][color]'`

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x = random.normal(size=100)
y = random.normal(size=100)

_, ax = plt.subplots()

ax.scatter(x, y)
ax.set(xlabel='This is the x-axis',ylabel='This is the y-axis',title='Plot of X vs Y')

[Text(0.5, 0, 'This is the x-axis'),
 Text(0, 0.5, 'This is the y-axis'),
 Text(0.5, 1.0, 'Plot of X vs Y')]

We will often want to save the output of a Python plot. We do this with the `plt.savefig()` function. We can choose the type of format to output by changing the extension of the file name. For instance, to create a pdf, we use `plt.savefig('output.pdf')`, and to create a jpeg, we use `plt.savefig('output.jpeg')`.

In [ ]:
plt.scatter(x, y, c='g')
# plt.savefig('Figure.pdf')

The function `np.arange` can be used to create a sequence of numbers. For instance, `np.arange(a, b)` makes a vector of integers between `a` and `b`, excluding `b`. Another funciton `np.linspace(a, b, n)` makes a sequence of `n` numbers that are equally spaced between `a` and `b`.

In [ ]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [ ]:
x = np.linspace(-np.pi, np.pi, 50)
x

array([-3.14159265, -3.01336438, -2.88513611, -2.75690784, -2.62867957,
       -2.5004513 , -2.37222302, -2.24399475, -2.11576648, -1.98753821,
       -1.85930994, -1.73108167, -1.60285339, -1.47462512, -1.34639685,
       -1.21816858, -1.08994031, -0.96171204, -0.83348377, -0.70525549,
       -0.57702722, -0.44879895, -0.32057068, -0.19234241, -0.06411414,
        0.06411414,  0.19234241,  0.32057068,  0.44879895,  0.57702722,
        0.70525549,  0.83348377,  0.96171204,  1.08994031,  1.21816858,
        1.34639685,  1.47462512,  1.60285339,  1.73108167,  1.85930994,
        1.98753821,  2.11576648,  2.24399475,  2.37222302,  2.5004513 ,
        2.62867957,  2.75690784,  2.88513611,  3.01336438,  3.14159265])

We will now create some more sophisticated plots. For instance, the `plt.contour()` function produces a contour plot in order to represent three-dimensional data; it is like a topographical map. It takes three arguments:
1. A vector of the `x` values (the first dimension),
2. A vector of the `y` values (the second dimension), and
3. A matrix of the `z` values (the third dimensions) for each pair of (`x`, `y`) coordintes.

As with the `plt.plot()` function, there are many other inputs that can be used to fine-tune the output of the `plt.contour()` function. To learn more about these, take a look at the help file by typing `?plt.contour`.

In [ ]:
y = x
f = np.matrix([[np.cos(j) / (1 + i**2) for j in y] for i in x])
_ = plt.contour(x, y, f)

In [ ]:
fa = (f - f.T) / 2
_ = plt.contour(x, y, fa, 15)

In [ ]:
np.shape(fa)

(50, 50)

The `plt.contourf()` function works the same way as `plt.contour()`, except that it produces a color-coded plot whose colors depend on the `z` value. This is known as heatmap, and is sometimes used to plot temperature in weather forecasts. Alternatively, `plt.` can be used to produce a three-dimensional plot. 

In [ ]:
_ = plt.contourf(x, y, fa)

The function `axes3d` create 3D plots, where `elev` and `azim` values control the angles to view the plots.

In [ ]:
X, Y = np.meshgrid(x, y)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.view_init(elev=30)
ax.plot_wireframe(X, Y, fa)

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.view_init(elev=30, azim=20)
ax.plot_wireframe(X, Y, fa)

### Indexing Data

We often wish to examine part of a set of data. Suppose that our data is stored in the matrix `A`.

In [ ]:
A = np.arange(1, 17).reshape(4, 4)
A = A.T
A

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

Then, type

In [ ]:
A[1, 2]

10

will select the element corresponding to the second row and the third column. The first number after the open-bracket symbol [ always refers to the row, and the second number always refers to the column.

In [ ]:
A[[0, 2]][:, [1, 3]]

array([[ 5, 13],
       [ 7, 15]])

In [ ]:
A[0:3, 1:4]

array([[ 5,  9, 13],
       [ 6, 10, 14],
       [ 7, 11, 15]])

In [ ]:
A[0:2, :]

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14]])

In [ ]:
A[:, 0:2]

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

The last two examples include either `:` for the columns or `:` for the rows. These indicate that Python should include all columns or all rows, respectively. Python treats a single row or column of a matrix as a vector.

In [ ]:
A[0,]

array([ 1,  5,  9, 13])

The wave symbol `~` in indeces tells Python to exclude the rows or columns that you specifiy.

In [ ]:
A[[~2, ~0]]

array([[ 2,  6, 10, 14],
       [ 4,  8, 12, 16]])

In [ ]:
A[[~2, ~0]][:, [1]]

array([[6],
       [8]])

In [ ]:
A

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

The `np.shape()` function outputs the number of rows followed by the number of columns of a given matrix

In [ ]:
np.shape(A)

(4, 4)

### Loading Data

For most analyses, the first step involves importing a data set into Python. The `pd.read_table()` function is one of the primary ways to do this. The help file contains details about how to use this function. We can export data using the `.to_{format}` method.

Before attempting to load a data set, we must make sure that Python knows to search for the data in the proper directory. We can do this by specifying the path in the argument of the `pd.read_table()` function. We begin by loading in the Auto data set. The following command will load the `Auto.csv` file into Python and store it as an object called `Auto`, in a format referred to as a `data frame`.

In [ ]:
import pandas as pd

In [ ]:
# auto = pd.read_csv('http://faculty.marshall.usc.edu/gareth-james/ISL/Auto.data')
auto = pd.read_csv('../data/Auto.csv')
auto.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0        130    3504          12.0    70   
1  15.0          8         350.0        165    3693          11.5    70   
2  18.0          8         318.0        150    3436          11.0    70   
3  16.0          8         304.0        150    3433          12.0    70   
4  17.0          8         302.0        140    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [ ]:
auto.shape

(397, 9)

Note that `Auto.csv` is simply a text file, which you could alternatively open on your computer using a standard text editor. It is often a good idea to view a data set using a text editor or other software such as Excel before loading it into Python.

The data set also includes a number of missing observations, indicated by a question mark '?'. Missing values are a common occurrence in real data sets.

In [ ]:
auto.values

array([[18.0, 8, 307.0, ..., 70, 1, 'chevrolet chevelle malibu'],
       [15.0, 8, 350.0, ..., 70, 1, 'buick skylark 320'],
       [18.0, 8, 318.0, ..., 70, 1, 'plymouth satellite'],
       ...,
       [32.0, 4, 135.0, ..., 82, 1, 'dodge rampage'],
       [28.0, 4, 120.0, ..., 82, 1, 'ford ranger'],
       [31.0, 4, 119.0, ..., 82, 1, 'chevy s-10']], dtype=object)

In [ ]:
auto.query("horsepower=='?'")

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
32   25.0          4          98.0          ?    2046          19.0    71   
126  21.0          6         200.0          ?    2875          17.0    74   
330  40.9          4          85.0          ?    1835          17.3    80   
336  23.6          4         140.0          ?    2905          14.3    80   
354  34.5          4         100.0          ?    2320          15.8    81   

     origin                  name  
32        1            ford pinto  
126       1         ford maverick  
330       2  renault lecar deluxe  
336       1    ford mustang cobra  
354       2           renault 18i

One option is to replace this values with `NaN`.

In [ ]:
auto = auto.replace('?', np.NaN)

The `shape` method tells us that the data has 397 observations, or rows, and nine variables, or columns. There are various ways to deal with the missing data. In this case, only five of the rows contain missing observations, and so we choose to use the `dropna` method to simply remove these rows.

In [ ]:
auto = auto.dropna()

In [ ]:
auto.shape

(392, 9)

Once the data are loaded correctly, we can use the method `columns` to check the variable names.

In [ ]:
auto.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin', 'name'],
      dtype='object')

### Additional Graphical and Numerical Summaries

We can use the plot() function to produce scatterplots of the quantitative variables. However, simply typing the variable names will produce an error message, because Python does not know to look in the Auto data set for those variables.

To refer to a variable, we must type the data set and the variable name joined with a `.` symbol.

In [ ]:
import seaborn as sns

In [ ]:
sns.scatterplot(data=auto, x='cylinders', y='mpg')

<AxesSubplot:xlabel='cylinders', ylabel='mpg'>

In [ ]:
auto.cylinders = auto.cylinders.astype('category')

In [ ]:
sns.boxplot(data=auto, x='cylinders', y='mpg')

<AxesSubplot:xlabel='cylinders', ylabel='mpg'>

In [ ]:
sns.histplot(data=auto, x='mpg', bins=15, color='red')

<AxesSubplot:xlabel='mpg', ylabel='Count'>

In [ ]:
sns.pairplot(auto)

In [ ]:
var_list = ['mpg', 'displacement', 'horsepower', 'weight', 'acceleration']

sns.pairplot(data=auto, vars=var_list)

In [ ]:
g = sns.scatterplot(data=auto, x='horsepower', y='mpg')

for i, txt in enumerate(auto.mpg):
    plt.annotate(txt, (auto.horsepower.iat[i], auto.mpg.iat[i]))

The `describe()` method produces a numerical summary of each variable in a particular data set.

In [ ]:
auto.describe(include='all')

mpg  cylinders  displacement horsepower       weight  \
count   392.000000      392.0    392.000000        392   392.000000   
unique         NaN        5.0           NaN         93          NaN   
top            NaN        4.0           NaN        150          NaN   
freq           NaN      199.0           NaN         22          NaN   
mean     23.445918        NaN    194.411990        NaN  2977.584184   
std       7.805007        NaN    104.644004        NaN   849.402560   
min       9.000000        NaN     68.000000        NaN  1613.000000   
25%      17.000000        NaN    105.000000        NaN  2225.250000   
50%      22.750000        NaN    151.000000        NaN  2803.500000   
75%      29.000000        NaN    275.750000        NaN  3614.750000   
max      46.600000        NaN    455.000000        NaN  5140.000000   

        acceleration        year      origin         name  
count     392.000000  392.000000  392.000000          392  
unique           NaN         NaN         NaN          301  
top              NaN         NaN         NaN  amc matador  
freq             NaN         NaN         NaN            5  
mean       15.541327   75.979592    1.576531          NaN  
std         2.758864    3.683737    0.805518          NaN  
min         8.000000   70.000000    1.000000          NaN  
25%        13.775000   73.000000    1.000000          NaN  
50%        15.500000   76.000000    1.000000          NaN  
75%        17.025000   79.000000    2.000000          NaN  
max        24.800000   82.000000    3.000000          NaN

In [ ]:
auto.name.describe()

count             392
unique            301
top       amc matador
freq                5
Name: name, dtype: object

In [ ]:
auto.mpg.describe()

count    392.000000
mean      23.445918
std        7.805007
min        9.000000
25%       17.000000
50%       22.750000
75%       29.000000
max       46.600000
Name: mpg, dtype: float64

## 2.4 Exercises

### Conceptual

#### 1. 

For each of parts (a) through (d), indicate whether we would generally expect the performance of a flexible statistical learning method to be better or worse than an inflexible method. Justify your answer.

a) The sample size n is extremely large, and the number of predictors p is small.  

>**Flexible**: we have enough observations to avoid overfitting, so assuming some there are non-linear relationships in our data a more flexible model should provide an improved fit.  

b) The number of predictors p is extremely large, and the number of observations n is small.  
>**Inflexible**: we *don't* have enough observations to avoid overfitting 

c) The relationship between the predictors and response is highly non-linear.  
>**Flexible**: a high variance model affords a better fit to non-linear relationships 

d) The variance of the error terms, i.e. σ2 = Var(ε), is extremely high.  
>**Inflexible**: a high bias model avoids overfitting to the noise in our dataset  

#### 2. 

Explain whether each scenario is a classification or regression problem, and indicate whether we are most interested in inference or prediction. Finally, provide n and p.

(a) We collect a set of data on the top 500 firms in the US. For each firm we record profit, number of employees, industry and the CEO salary. We are interested in understanding which factors affect CEO salary.  

>regression, inference, n=500, p=4 
>
>Regression because it is a quantitative outcome, and Inference because the objective is not predict but interpretate the relalation between the factors and the salary.

(b) We are considering launching a new product and wish to know whether it will be a success or a failure. We collect data on 20 similar products that were previously launched. For each product we have recorded whether it was a success or failure, price charged for the product, marketing budget, competition price, and ten other variables.  

>classification, prediction, n=20, p=14
>
> It is a qualitative issue (binary one) and the main interest is get an accuracy response.

(c) We are interested in predicting the % change in the USD/Euro exchange rate in relation to the weekly changes in the world stock markets. Hence we collect weekly data for all of 2012. For each week we record the % change in the USD/Euro, the % change in the US market, the % change in the British market, and the % change in the German market. 

>regression, prediction, n=52, p=4

#### 3. 

We now revisit the bias-variance decomposition.

(a) Provide a sketch of typical (squared) bias, variance, training error, test error, and Bayes (or irreducible) error curves, on a single plot, as we go from less flexible statistical learning methods towards more flexible approaches. The x-axis should represent the amount of flexibility in the method, and the y-axis should represent the values for each curve. There should be five curves. Make sure to label each one.

<img src=https://pseudotitle.files.wordpress.com/2016/12/bias-variance-decomposition.png>

(b)


>- The Bayes-error is **constant** because it is particular from the dataset and does not alter by modelling features.
>
>- The training error just decreases as the level of flexibility increases and the function overfits the data, at the end the error assumes a minimum constant value.
>
>- The test error begins decreasing until a mark level where flexibility starts to overfit the training data (following its noise) and the error starts to increase.
>
>- The Bias just decreases as the levels of flexibility creates a more complex function, which represents better the real-problem.
>
>- The Variance starts to increase slowly, after with higher levels of flexibility, the function become less robust and the variance value increases rapidly.

#### 4. 

You will now think of some real-life applications for statistical learning.

(a) Describe three real-life applications in which classification might be useful. Describe the response, as well as the predictors. Is the goal of each application inference or prediction? Explain your answer.  

  1. Is this tumor malignant or benign?
    - response: boolean (is malign)
    - predictors (naive examples): tumor size, white blood cell count, change in adrenal mass, position in body
    - goal: prediction
  2. What animals are in this image?
    - response: 'Cat', 'Dog', 'Fish'
    - predictors: image pixel values
    - goal: prediction
  3. What test bench metrics are most indicative of a faulty Printed Circuit Board (PCB)?
    - response: boolean (is faulty)
    - predictors: current draw, voltage drawer, output noise, operating temp.
    - goal: inference




(b) Describe three real-life applications in which regression might be useful. Describe the response, as well as the predictors. Is the goal of each application inference or prediction? Explain your answer.  

  1. How much is this house worth?
    - responce: SalePrice
    - predictors: LivingArea, BathroomCount, GarageCount, Neighbourhood, CrimeRate
    - goal: prediction
  2. What attributes most affect the market cap. of a company?
    - response: MarketCap
    - predictors: Sector, Employees, FounderIsCEO, Age, TotalInvestment, Profitability, RONA
    - goal: inference
  3. How long is this dairy cow likely to live?
    - response: years
    - predictors: past medical conditions, current weight, milk yield
    - goal: prediction



(c) Describe three real-life applications in which cluster analysis might be useful.  

  1. This dataset contains observations of 3 different species of flower. Estimate which observations belong to the same species.
    - response: a, b, c (species class)
    - predictors: sepal length, petal length, number of petals
    - goal: prediction
  2. which attributes of the flowers in dataset described above are most predictive of species?
    - response: a, b, c (species class)
    - predictors: sepal length, petal length, number of petals
    - goal: inference
  3. Group these audio recordings of birdsong by species.
    - responce: (species classes)
    - predictors: audio sample values
    - goal: prediction

#### 5. 

What are the advantages and disadvantages of a very flexible (versus a less flexible) approach for regression or classification? Under what circumstances might a more flexible approach be preferred to a less flexible approach? When might a less flexible approach be preferred?

The advantages for a very flexible approach for regression or classification are obtaining a better fit for non-linear models, decreasing bias.

The disadvantages for a very flexible approach for regression or classification are requires estimating a greater number of parameters, follow the noise too closely (overfit), increasing variance.

A more flexible approach would be preferred to a less flexible approach when we are interested in prediction and not the interpretability of the results.

A less flexible approach would be preferred to a more flexible approach when we are interested in inference and the interpretability of the results.

#### 6. 

Describe the differences between a parametric and a non-parametric statistical learning approach. What are the advantages of a parametric approach to regression or classification (as opposed to a non-parametric approach)? What are its disadvantages?

A parametric approach reduces the problem of estimating f down to one of estimating a set of parameters because it assumes a form for f.

A non-parametric approach does not assume a functional form for f and so requires a very large number of observations to accurately estimate f.

The advantages of a parametric approach to regression or classification are the simplifying of modeling f to a few parameters and not as many observations are
required compared to a non-parametric approach.

The disadvantages of a parametric approach to regression or classification are a potential to inaccurately estimate f if the form of f assumed is wrong or
to overfit the observations if more flexible models are used.

#### 7. 

The table below provides a training data set containing six observations, three predictors, and one qualitative response variable.

(a)

In [ ]:
obs0 = np.array([0, 0, 0])
obs1 = np.array([0, 3, 0])
obs2 = np.array([2, 0, 0])
obs3 = np.array([0, 1, 3])
obs4 = np.array([0, 1, 2])
obs5 = np.array([-1, 0, 1])
obs6 = np.array([1, 1, 1])

obs = [obs1, obs2, obs3, obs4, obs5, obs6]
dist = {}

for i in range(6):
    dist['obs' + str(i + 1)] = np.sqrt(np.sum((obs[i] - obs0)**2))
    print('obs' + str(i + 1) + ':', dist['obs' + str(i + 1)])

obs1: 3.0
obs2: 2.0
obs3: 3.1622776601683795
obs4: 2.23606797749979
obs5: 1.4142135623730951
obs6: 1.7320508075688772


(b), (c)

In [ ]:
sorted(dist.items(), key=lambda item: item[1])

[('obs5', 1.4142135623730951),
 ('obs6', 1.7320508075688772),
 ('obs2', 2.0),
 ('obs4', 2.23606797749979),
 ('obs1', 3.0),
 ('obs3', 3.1622776601683795)]

prediction = Green;

prediction = Red;

(d)

Small. A small K would be flexible for a non-linear decision boundary,
whereas a large K would try to fit a more linear boundary because it takes more
points into consideration.

### Applied

#### 8. College dataset

(a)

In [ ]:
import janitor as jn
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
# college = pd.read_csv('http://faculty.marshall.usc.edu/gareth-james/ISL/College.csv')
college = pd.read_csv('../data//college.csv')
college.head()

Unnamed: 0 Private  Apps  Accept  Enroll  Top10perc  \
0  Abilene Christian University     Yes  1660    1232     721         23   
1            Adelphi University     Yes  2186    1924     512         16   
2                Adrian College     Yes  1428    1097     336         22   
3           Agnes Scott College     Yes   417     349     137         60   
4     Alaska Pacific University     Yes   193     146      55         16   

   Top25perc  F.Undergrad  P.Undergrad  Outstate  Room.Board  Books  Personal  \
0         52         2885          537      7440        3300    450      2200   
1         29         2683         1227     12280        6450    750      1500   
2         50         1036           99     11250        3750    400      1165   
3         89          510           63     12960        5450    450       875   
4         44          249          869      7560        4120    800      1500   

   PhD  Terminal  S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0   70        78       18.1           12    7041         60  
1   29        30       12.2           16   10527         56  
2   53        66       12.9           30    8735         54  
3   92        97        7.7           37   19016         59  
4   76        72       11.9            2   10922         15

(b)

In [ ]:
college = college.rename_column('Unnamed: 0', 'College')
college.head()

College Private  Apps  Accept  Enroll  Top10perc  \
0  Abilene Christian University     Yes  1660    1232     721         23   
1            Adelphi University     Yes  2186    1924     512         16   
2                Adrian College     Yes  1428    1097     336         22   
3           Agnes Scott College     Yes   417     349     137         60   
4     Alaska Pacific University     Yes   193     146      55         16   

   Top25perc  F.Undergrad  P.Undergrad  Outstate  Room.Board  Books  Personal  \
0         52         2885          537      7440        3300    450      2200   
1         29         2683         1227     12280        6450    750      1500   
2         50         1036           99     11250        3750    400      1165   
3         89          510           63     12960        5450    450       875   
4         44          249          869      7560        4120    800      1500   

   PhD  Terminal  S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0   70        78       18.1           12    7041         60  
1   29        30       12.2           16   10527         56  
2   53        66       12.9           30    8735         54  
3   92        97        7.7           37   19016         59  
4   76        72       11.9            2   10922         15

(c) i

In [ ]:
college.describe()

Apps        Accept       Enroll   Top10perc   Top25perc  \
count    777.000000    777.000000   777.000000  777.000000  777.000000   
mean    3001.638353   2018.804376   779.972973   27.558559   55.796654   
std     3870.201484   2451.113971   929.176190   17.640364   19.804778   
min       81.000000     72.000000    35.000000    1.000000    9.000000   
25%      776.000000    604.000000   242.000000   15.000000   41.000000   
50%     1558.000000   1110.000000   434.000000   23.000000   54.000000   
75%     3624.000000   2424.000000   902.000000   35.000000   69.000000   
max    48094.000000  26330.000000  6392.000000   96.000000  100.000000   

        F.Undergrad   P.Undergrad      Outstate   Room.Board        Books  \
count    777.000000    777.000000    777.000000   777.000000   777.000000   
mean    3699.907336    855.298584  10440.669241  4357.526384   549.380952   
std     4850.420531   1522.431887   4023.016484  1096.696416   165.105360   
min      139.000000      1.000000   2340.000000  1780.000000    96.000000   
25%      992.000000     95.000000   7320.000000  3597.000000   470.000000   
50%     1707.000000    353.000000   9990.000000  4200.000000   500.000000   
75%     4005.000000    967.000000  12925.000000  5050.000000   600.000000   
max    31643.000000  21836.000000  21700.000000  8124.000000  2340.000000   

          Personal         PhD    Terminal   S.F.Ratio  perc.alumni  \
count   777.000000  777.000000  777.000000  777.000000   777.000000   
mean   1340.642214   72.660232   79.702703   14.089704    22.743887   
std     677.071454   16.328155   14.722359    3.958349    12.391801   
min     250.000000    8.000000   24.000000    2.500000     0.000000   
25%     850.000000   62.000000   71.000000   11.500000    13.000000   
50%    1200.000000   75.000000   82.000000   13.600000    21.000000   
75%    1700.000000   85.000000   92.000000   16.500000    31.000000   
max    6800.000000  103.000000  100.000000   39.800000    64.000000   

             Expend  Grad.Rate  
count    777.000000  777.00000  
mean    9660.171171   65.46332  
std     5221.768440   17.17771  
min     3186.000000   10.00000  
25%     6751.000000   53.00000  
50%     8377.000000   65.00000  
75%    10830.000000   78.00000  
max    56233.000000  118.00000

(c) ii

In [ ]:
sns.pairplot(college.iloc[:, 1:11])

(c) iii

In [ ]:
sns.boxplot(data=college, x='Private', y='Outstate')

<AxesSubplot:xlabel='Private', ylabel='Outstate'>

(c) iv

In [ ]:
college.add_column('Elite', value=(college.Top10perc > 50));

In [ ]:
college.Elite.astype('bool')

AttributeError: 'DataFrame' object has no attribute 'Elite'

In [ ]:
sns.boxplot(college.Elite, college.Outstate);

(c) v

In [ ]:
# Normalization
def norm(df):
    return (df - df.mean()) / (df.std())


features = 13
college_norm = norm(college.iloc[:, 2:features + 1])
college_norm.head()

`pandas.melt()` Unpivot a DataFrame from wide format to long format, optionally leaving identifier variables set.

In [ ]:
college_melt = college_norm.pivot_longer(values_to='vals')
college_melt.head()

In [ ]:
sns.displot(data=college_melt,
            x='vals',
            col='variable',
            col_wrap=4,
            kde=True,
            stat="density",
            common_norm=False)

In [ ]:
g = sns.FacetGrid(college_melt, col='variable', col_wrap=4)
g.map(sns.distplot, 'vals')
g.set(xlim=(-4, 4))

#### 9. Auto dataset

In [ ]:
auto = pd.read_csv('../data/Auto.csv')
auto.head()

In [ ]:
auto[auto.values == '?']
auto = auto.replace('?', np.NaN)
auto = auto.dropna()

In [ ]:
# (a) Which of the predictors are quantitative, and which are qualitative?
datatypes = {
    'quant': [
        'mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
        'acceleration'
    ],
    'qual': ['origin', 'name']
}

auto_quant = auto[datatypes['quant']].astype(np.float_)

In [ ]:
# (b) What is the range of each quantitative predictor?
# (c) What is the mean and standard deviation of each quantitative predictor?

pd.DataFrame({
    'range': auto_quant.max() - auto_quant.min(),
    'mean': auto_quant.mean(),
    'std': auto_quant.std()
})

In [ ]:
# (d) Now remove the 10th through 85th observations.
# What is the range, mean, and standard deviation of each predictor
# in the subset of the data that remains?

# drop observations 10 to 85
auto_quant_d = auto_quant.drop(auto_quant.index[10:85])
# results as dataframe
pd.DataFrame({
    'range': auto_quant_d.max() - auto_quant_d.min(),
    'mean': auto_quant_d.mean(),
    'std': auto_quant_d.std()
})

In [ ]:
# (e) Using the full data set, investigate the predictors graphically,
# using scatterplots or other tools of your choice. Create some plots
# highlighting the relationships among the predictors. Comment on your findings.

# combine numeric quantitive data with original qualitive data
auto_n = pd.concat([auto_quant, auto[datatypes['qual']]], axis=1)
# pairplot grid
sns.pairplot(auto_n)

(f)

Looking at the plots above, displacement, horsepower and weight seem most strongly correlated with mpg. It also seems to be a discernible relationship with cylinders and origin which we might try including in our analysis.

Accelration is not strongly correllated with mpg, so we might consider dropping this feature.

#### 10. Boston dataset

(a)

In [ ]:
from sklearn.datasets import load_boston

In [ ]:
boston_raw = load_boston()
print(boston_raw.keys())

In [ ]:
print(boston_raw.DESCR)

In [ ]:
boston_data = np.column_stack([boston_raw.data, boston_raw.target])
col_names = np.append(boston_raw.feature_names, 'MEDV')

# create the data frame
boston = pd.DataFrame(boston_data, columns=col_names)
boston.head()

In [ ]:
boston.shape

(b)

In [ ]:
sns.pairplot(boston)

(c)

In [ ]:
corr_matrix = boston.corr()
corr_matrix.CRIM.sort_values(ascending=False)

(d)

In [ ]:
sns.histplot(boston.CRIM)

In [ ]:
sns.histplot(boston.TAX)

In [ ]:
sns.histplot(boston.PTRATIO)

In [ ]:
sum(boston.CHAS == 1)

(f)

In [ ]:
boston.PTRATIO.median()

(g)

In [ ]:
boston.MEDV.min(), boston.MEDV.idxmin()

In [ ]:
print(boston.iloc[398])

(h)

In [ ]:
sum(boston.RM > 7)

In [ ]:
sum(boston.RM > 8)

In [ ]:
UpperClass = boston.query('RM>8')
UpperClass.describe()