In [14]:
import torch

In [15]:

print(torch.__version__)
print(torch.backends.mps.is_available())  # Apple MPS（Metal 加速）是否启用


2.2.2
True


In [16]:
x = torch.arange(12)

In [17]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
x.shape

torch.Size([12])

In [19]:
X = x.reshape(3, 4)

In [20]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [21]:
zeros_3_4 = torch.zeros(3,3, 4)

In [22]:
zeros_3_4

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [24]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

In [25]:
A = torch.arange(20).reshape(5, 4)
B = torch.arange(20).reshape(5, 4)

In [26]:
A / B

tensor([[nan, 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])